const trackNames = {
  ["Catamarca", "Camino a Coneta", "n", "2.81", "4.50", "", "Argentina"],
  ["Catamarca", "Camino a La Puerta", "n", "5.19", "8.30", "", "Argentina"],
  ["Catamarca", "Camino de acantilados y rocas", "n", "3.31", "5.30", "", "Argentina"],
  ["Catamarca", "Camino de acantilados y rocas inverso", "n", "3.31", "5.30", "", "Argentina"],
  ["Catamarca", "El Rodeo", "n", "1.75", "2.80", "Very twisty and bumpy", "Argentina"],
  ["Catamarca", "Huillaprima", "n", "2.13", "3.40", "", "Argentina"],
  ["Catamarca", "La Merced", "n", "1.75", "2.80", "", "Argentina"],
  ["Catamarca", "Las Juntas", "n", "5.19", "8.30", "", "Argentina"],
  ["Catamarca", "Miraflores", "n", "2.13", "3.40", "", "Argentina"],
  ["Catamarca", "San Isidro", "n", "2.81", "4.50", "", "Argentina"],
  ["Catamarca", "Valle de los puentes", "n", "5.00", "8.00", "", "Argentina"],
  ["Catamarca", "Valle de los puentes a la inversa", "n", "5.00", "8.00", "", "Argentina"],
  ["Argolis", "Abies Koilada", "n", "4.44", "7.10", "", "Unknown"],
  ["Argolis", "Ampelonas Ormi", "n", "3.13", "5.00", "", "Unknown"],
  ["Argolis", "Anodou Farmakas", "n", "6.00", "9.60", "", "Unknown"],
  ["Argolis", "Fourketa Kourva", "n", "3.00", "4.80", "", "Unknown"],
  ["Argolis", "Kathodo Leontiou", "n", "6.00", "9.60", "", "Unknown"],
  ["Argolis", "Koryfi Dafini", "n", "2.81", "4.50", "", "Unknown"],
  ["Argolis", "Ourea Spevsi", "n", "3.56", "5.70", "", "Unknown"],
  ["Argolis", "Pedines Epidaxi", "n", "3.38", "5.40", "", "Unknown"],
  ["Argolis", "Perasma Platani", "n", "6.69", "10.70", "", "Unknown"],
  ["Argolis", "Pomona Ekrixi", "n", "3.19", "5.10", "", "Unknown"],
  ["Argolis", "Tsiristra Thea", "n", "6.50", "10.40", "", "Unknown"],
  ["Argolis", "Ypsona tou Dasos", "n", "4.13", "6.60", "", "Unknown"],
  ["Baumholder", "Frauenberg", "n", "7.31", "11.70", "", "Unknown"],
  ["Baumholder", "Hammerstein", "n", "6.75", "10.80", "", "Unknown"],
  ["Baumholder", "Innerer Feld-Sprint", "n", "3.50", "5.60", "", "Unknown"],
  ["Baumholder", "Innerer Feld-Sprint (umgekehrt)", "n", "3.50", "5.60", "", "Unknown"],
  ["Baumholder", "Kreuzungsring", "n", "3.94", "6.30", "", "Unknown"],
  ["Baumholder", "Kreuzungsring reverse", "n", "3.94", "6.30", "", "Unknown"],
  ["Baumholder", "Oberstein", "n", "7.31", "11.70", "", "Unknown"],
  ["Baumholder", "Ruschberg", "n", "6.69", "10.70", "", "Unknown"],
  ["Baumholder", "Verbundsring", "n", "3.63", "5.80", "", "Unknown"],
  ["Baumholder", "Verbundsring reverse", "n", "3.63", "5.80", "", "Unknown"],
  ["Baumholder", "Waldabstieg", "n", "3.38", "5.40", "", "Unknown"],
  ["Baumholder", "Waldaufsteig", "n", "3.38", "5.40", "", "Unknown"],
  ["Bikernieki Rallycross", "Full Circuit", "Y", "0.81", "1.30", "", "Unknown"],
  ["Circuit De Barcelona-Catalunya Rallycross", "Full Circuit", "Y", "0.69", "1.10", "", "Unknown"],
  ["Estering Rallycross", "Full Circuit", "Y", "0.56", "0.90", "", "Unknown"],
  ["Hawkes Bay", "Elsthorpe Sprint Forward", "n", "4.56", "7.30", "", "New Zealand"],
  ["Hawkes Bay", "Elsthorpe Sprint Reverse", "n", "4.56", "7.30", "", "New Zealand"],
  ["Hawkes Bay", "Ocean Beach", "n", "7.19", "11.50", "", "New Zealand"],
  ["Hawkes Bay", "Ocean Beach Sprint", "n", "4.13", "6.60", "", "New Zealand"],
  ["Hawkes Bay", "Ocean Beach Sprint Reverse", "n", "4.13", "6.60", "", "New Zealand"],
  ["Hawkes Bay", "Te Awanga Forward", "n", "7.19", "11.50", "benchmark with Luke", "New Zealand"],
  ["Hawkes Bay", "Te Awanga Sprint Forward", "n", "3.00", "4.80", "", "New Zealand"],
  ["Hawkes Bay", "Te Awanga Sprint Reverse", "n", "3.00", "4.80", "", "New Zealand"],
  ["Hawkes Bay", "Waimarama Point Forward", "n", "10.06", "16.10", "", "New Zealand"],
  ["Hawkes Bay", "Waimarama Point Reverse", "n", "10.06", "16.10", "", "New Zealand"],
  ["Hawkes Bay", "Waimarama Sprint Forward", "n", "5.50", "8.80", "", "New Zealand"],
  ["Hawkes Bay", "Waimarama Sprint Reverse", "n", "5.50", "8.80", "", "New Zealand"],
  ["Hell Rallycross", "Rallycross", "Y", "0.63", "1.00", "", "Unknown"],
  ["Höljes Rallycross", "Rallycross", "Y", "0.75", "1.20", "", "Unknown"],
  ["Jämsä", "Hämelahti", "n", "9.38", "15.00", "", "Unknown"],
  ["Jämsä", "Iso Oksajärvi", "n", "5.00", "8.00", "", "Unknown"],
  ["Jämsä", "Järvenkylä", "n", "5.06", "8.10", "", "Unknown"],
  ["Jämsä", "Jyrkysjärvi", "n", "4.69", "7.50", "", "Unknown"],
  ["Jämsä", "Kailajärvi", "n", "4.69", "7.50", "", "Unknown"],
  ["Jämsä", "Kakaristo", "n", "10.13", "16.20", "", "Unknown"],
  ["Jämsä", "Kontinjärvi", "n", "9.38", "15.00", "", "Unknown"],
  ["Jämsä", "Kotajärvi", "n", "5.06", "8.10", "", "Unknown"],
  ["Jämsä", "Naarajärvi", "n", "4.63", "7.40", "", "Unknown"],
  ["Jämsä", "Oksala", "n", "5.06", "8.10", "", "Unknown"],
  ["Jämsä", "Paskuri", "n", "4.56", "7.30", "", "Unknown"],
  ["Jämsä", "Pitkäjärvi", "n", "10.13", "16.20", "", "Unknown"],
  ["Killarney International Raceway Rallycross", "Rallycross", "Y", "0.69", "1.10", "", "Unknown"],
  ["Leczna County", "Borysik", "n", "5.81", "9.30", "", "Poland"],
  ["Leczna County", "Czarny Las", "n", "4.13", "6.60", "", "Poland"],
  ["Leczna County", "Jagodno", "n", "4.25", "6.80", "", "Poland"],
  ["Leczna County", "Jezioro Lukie", "n", "4.13", "6.60", "", "Poland"],
  ["Leczna County", "Jezioro Rotcze", "n", "8.38", "13.40", "", "Poland"],
  ["Leczna County", "Józefin", "n", "4.38", "7.00", "", "Poland"],
  ["Leczna County", "Kopina", "n", "4.38", "7.00", "", "Poland"],
  ["Leczna County", "Lejno", "n", "4.25", "6.80", "", "Poland"],
  ["Leczna County", "Marynka", "n", "5.81", "9.30", "Lots of nice straights", "Poland"],
  ["Leczna County", "Zagorze", "n", "10.31", "16.50", "", "Poland"],
  ["Leczna County", "Zaróbka", "n", "10.31", "16.50", "", "Poland"],
  ["Leczna County", "Zienki", "n", "8.38", "13.40", "", "Poland"],
  ["Lohéac Bretagne Rallycross", "Rallycross", "Y", "0.69", "1.10", "Nice loop I raced early on", "Unknown"],
  ["Lydden Hill Rallycross", "Rallycross", "Y", "0.88", "1.40", "", "Unknown"],
  ["Mettet Rallycross", "Rallycross", "Y", "0.69", "1.10", "", "Belguim"],
  ["Monaro", "Bondi Forest", "n", "4.38", "7.00", "nice and fast track", "Australia"],
  ["Monaro", "Chandlers Creek", "n", "7.69", "12.30", "", "Australia"],
  ["Monaro", "Chandlers Creek Reverse", "n", "7.69", "12.30", "", "Australia"],
  ["Monaro", "Mount Kaye Pass", "n", "7.81", "12.50", "", "Australia"],
  ["Monaro", "Mount Kaye Pass Reverse", "n", "7.81", "12.50", "", "Australia"],
  ["Monaro", "Noorinbee Ridge Ascent", "n", "3.31", "5.30", "", "Australia"],
  ["Monaro", "Noorinbee Ridge Descent", "n", "3.31", "5.30", "", "Australia"],
  ["Monaro", "Rockton Plains", "n", "4.31", "6.90", "nice tarmack sections. Tricker then you think", "Australia"],
  ["Monaro", "Rockton Plains Reverse", "n", "4.31", "6.90", "", "Australia"],
  ["Monaro", "Taylor Farm Sprint", "n", "4.38", "7.00", "", "Australia"],
  ["Monaro", "Yambulla Mountain Ascent", "n", "4.25", "6.80", "", "Australia"],
  ["Monaro", "Yambulla Mountain Descent", "n", "4.13", "6.60", "", "Australia"],
  ["Montalegre Rallycross", "Rallycross", "Y", "0.56", "0.90", "", "Unknown"],
  ["Monte Carlo", "Approache du Col de Turini Montee", "n", "2.50", "4.00", "", "Unknown"],
  ["Monte Carlo", "Col de Turini Depart", "n", "6.13", "9.80", "", "Unknown"],
  ["Monte Carlo", "Col de Turini - Depart en descente", "n", "4.25", "6.80", "", "Unknown"],
  ["Monte Carlo", "Col de Turini - Descente", "n", "3.25", "5.20", "", "Unknown"],
  ["Monte Carlo", "Col de Turini - Sprint en descente", "n", "2.94", "4.70", "", "Unknown"],
  ["Monte Carlo", "Col de Turini - Sprint en montee", "n", "2.94", "4.70", "", "Unknown"],
  ["Monte Carlo", "Gordolon - Courte Montee", "n", "3.25", "5.20", "", "Unknown"],
  ["Monte Carlo", "Pra d'Alart", "n", "6.13", "9.80", "", "Unknown"],
  ["Monte Carlo", "Route de Turini", "n", "6.81", "10.90", "", "Unknown"],
  ["Monte Carlo", "Route de Turini Decente", "n", "2.50", "4.00", "", "Unknown"],
  ["Monte Carlo", "Route de Turini Montee", "n", "4.25", "6.80", "", "Unknown"],
  ["Monte Carlo", "Vallee Descendante", "n", "6.81", "10.90", "", "Unknown"],
  ["New England", "Beaver Creek Trailer Forward", "n", "8.06", "12.90", "", "USA"],
  ["New England", "Beaver Creek Trail Reverse", "n", "8.06", "12.90", "", "USA"],
  ["New England", "Fuller Mountain Ascent", "n", "4.13", "6.60", "amazing with nice straights", "USA"],
  ["New England", "Fuller Mountain Descent", "n", "4.13", "6.60", "", "USA"],
  ["New England", "Fury Lake Depart", "n", "4.31", "6.90", "", "USA"],
  ["New England", "Hancock Creek Burst", "n", "4.31", "6.90", "", "USA"],
  ["New England", "Hancock Hill Sprint Forward", "n", "3.75", "6.00", "", "USA"],
  ["New England", "Hancock Hill Sprint Reverse", "n", "3.81", "6.10", "", "USA"],
  ["New England", "North Fork Pass", "n", "7.81", "12.50", "", "USA"],
  ["New England", "North Fork Pass Reverse", "n", "7.81", "12.50", "", "USA"],
  ["New England", "Tolt Valley Sprint Forward", "n", "3.81", "6.10", "", "USA"],
  ["New England", "Tolt Valley Sprint Reverse", "n", "3.75", "6.00", "", "USA"],
  ["Perth And Kinross", "Annbank Station", "n", "4.88", "7.80", "", "Unknown"],
  ["Perth And Kinross", "Annbank Station Reverse", "n", "4.75", "7.60", "", "Unknown"],
  ["Perth And Kinross", "Glencastle Farm", "n", "3.31", "5.30", "", "Unknown"],
  ["Perth And Kinross", "Glencastle Farm Reverse", "n", "3.25", "5.20", "", "Unknown"],
  ["Perth And Kinross", "Newhouse Bridge", "n", "8.06", "12.90", "", "Unknown"],
  ["Perth And Kinross", "Newhouse Bridge Reverse", "n", "8.13", "13.00", "", "Unknown"],
  ["Perth And Kinross", "Old Butterstone Muir", "n", "3.63", "5.80", "", "Unknown"],
  ["Perth And Kinross", "Old Butterstone Muir Reverse", "n", "3.56", "5.70", "", "Unknown"],
  ["Perth And Kinross", "Rosebank Farm", "n", "4.50", "7.20", "", "Unknown"],
  ["Perth And Kinross", "Rosebank Farm Reverse", "n", "4.38", "7.00", "", "Unknown"],
  ["Perth And Kinross", "South Morningside", "n", "7.88", "12.60", "", "Unknown"],
  ["Perth And Kinross", "South Morningside Reverse", "n", "7.94", "12.70", "", "Unknown"],
  ["Powys", "Bidno Moorland", "n", "3.06", "4.90", "", "Unknown"],
  ["Powys", "Bidno Moorland Reverse", "n", "3.00", "4.80", "", "Unknown"],
  ["Powys", "Bronfelen", "n", "7.13", "11.40", "", "Unknown"],
  ["Powys", "Dyffryn Afon", "n", "3.56", "5.70", "", "Unknown"],
  ["Powys", "Dyffryn Afon Reverse", "n", "3.56", "5.70", "", "Unknown"],
  ["Powys", "Fferm Wynt", "n", "3.56", "5.70", "", "Unknown"],
  ["Powys", "Fferm Wynt Reverse", "n", "3.56", "5.70", "", "Unknown"],
  ["Powys", "Geufron Forest", "n", "6.25", "10.00", "", "Unknown"],
  ["Powys", "Pant Mawr", "n", "2.94", "4.70", "", "Unknown"],
  ["Powys", "Pant Mawr Reverse", "n", "3.19", "5.10", "", "Unknown"],
  ["Powys", "River Severn Valley", "n", "7.13", "11.40", "", "Unknown"],
  ["Powys", "Sweet Lamb", "n", "6.19", "9.90", "", "Unknown"],
  ["Ribadelles", "Ascenso bosque Montevard", "n", "4.25", "6.80", "", "Spain"],
  ["Ribadelles", "Ascenso por valle el Gualet", "n", "4.38", "7.00", "", "Spain"],
  ["Ribadelles", "Camino a Centenera", "n", "6.63", "10.60", "", "Spain"],
  ["Ribadelles", "Centenera", "n", "6.63", "10.60", "", "Spain"],
  ["Ribadelles", "Comienzo en Bellriu", "n", "8.94", "14.30", "", "Spain"],
  ["Ribadelles", "Descento por carretera", "n", "2.88", "4.60", "", "Spain"],
  ["Ribadelles", "Final en Bellriu", "n", "8.94", "14.30", "", "Spain"],
  ["Ribadelles", "Salida desde Montverd", "n", "4.38", "7.00", "", "Spain"],
  ["Ribadelles", "Subida por Carretera", "n", "2.88", "4.60", "", "Spain"],
  ["Ribadelles", "Vinedos Dardenya", "n", "4.06", "6.50", "", "Spain"],
  ["Ribadelles", "Vinedos Dardenya inversa", "n", "4.06", "6.50", "", "Spain"],
  ["Ribadelles", "Vinedos dentro del valle Parra", "n", "4.25", "6.80", "", "Spain"],
  ["Silverstone Rallycross", "Rallycross", "Y", "0.63", "1.00", "", "Unknown"],
  ["Trois-Rivières Rallycross", "Rallycross", "Y", "0.88", "1.40", "", "Unknown"],
  ["Varmland", "Älgsjön", "n", "4.56", "7.30", "", "Unknown"],
  ["Varmland", "Älgsjön Sprint", "n", "3.31", "5.30", "", "Unknown"],
  ["Varmland", "Bjorklangen", "n", "3.25", "5.20", "", "Unknown"],
  ["Varmland", "Elgsjon", "n", "4.56", "7.30", "", "Unknown"],
  ["Varmland", "Hamra", "n", "7.69", "12.30", "", "Unknown"],
  ["Varmland", "Lysvik", "n", "7.69", "12.30", "", "Unknown"],
  ["Varmland", "Norraskoga", "n", "7.50", "12.00", "", "Unknown"],
  ["Varmland", "Ostra Hinnsjon", "n", "3.25", "5.20", "", "Unknown"],
  ["Varmland", "Ransbysater", "n", "7.50", "12.00", "", "Unknown"],
  ["Varmland", "Skogsrallyt", "n", "3.31", "5.30", "", "Unknown"],
  ["Varmland", "Stor-Jangen Sprint", "n", "4.19", "6.70", "", "Unknown"],
  ["Varmland", "Stor-Jangen sprint reverse", "n", "4.19", "6.70", "", "Unknown"],
  ["Yas Marina Circuit Rallycross", "Rallycross", "Y", "0.63", "1.00", "", "Unknown"],
};
